import type { EstimateLineItem } from "@/hooks/useEstimates";

// ── Trades templates ──
// Extracted to keep the hook lean and allow independent imports

export interface TradesTemplate {
  key: string;
  label: string;
  description: string;
  defaultItems: Omit<EstimateLineItem, "id" | "estimate_id" | "line_total">[];
}

export const TRADES_TEMPLATES: TradesTemplate[] = [
  {
    key: "plumbing",
    label: "Plumbing",
    description: "Standard plumbing service estimate",
    defaultItems: [
      {
        title: "Service Call",
        description: "Initial diagnostic and assessment",
        quantity: 1,
        unit: "visit",
        unit_price: 0,
        labor_hours: 1,
        labor_rate: 95,
        material_cost: 0,
        markup_percent: 0,
        tax_percent: 0,
        sort_order: 0,
      },
      {
        title: "Labor",
        description: "Plumbing labor",
        quantity: 1,
        unit: "hour",
        unit_price: 0,
        labor_hours: 2,
        labor_rate: 95,
        material_cost: 0,
        markup_percent: 0,
        tax_percent: 0,
        sort_order: 1,
      },
      {
        title: "Materials",
        description: "Parts and supplies",
        quantity: 1,
        unit: "lot",
        unit_price: 0,
        labor_hours: 0,
        labor_rate: 0,
        material_cost: 150,
        markup_percent: 20,
        tax_percent: 0,
        sort_order: 2,
      },
    ],
  },
  {
    key: "hvac",
    label: "HVAC",
    description: "Heating, ventilation, and air conditioning",
    defaultItems: [
      {
        title: "System Inspection",
        description: "Complete HVAC system evaluation",
        quantity: 1,
        unit: "visit",
        unit_price: 0,
        labor_hours: 1.5,
        labor_rate: 110,
        material_cost: 0,
        markup_percent: 0,
        tax_percent: 0,
        sort_order: 0,
      },
      {
        title: "Labor",
        description: "HVAC technician labor",
        quantity: 1,
        unit: "hour",
        unit_price: 0,
        labor_hours: 3,
        labor_rate: 110,
        material_cost: 0,
        markup_percent: 0,
        tax_percent: 0,
        sort_order: 1,
      },
      {
        title: "Equipment & Parts",
        description: "HVAC components and materials",
        quantity: 1,
        unit: "lot",
        unit_price: 0,
        labor_hours: 0,
        labor_rate: 0,
        material_cost: 500,
        markup_percent: 25,
        tax_percent: 0,
        sort_order: 2,
      },
    ],
  },
  {
    key: "electrical",
    label: "Electrical",
    description: "Electrical service and installation",
    defaultItems: [
      {
        title: "Service Call",
        description: "Electrical diagnostic and assessment",
        quantity: 1,
        unit: "visit",
        unit_price: 0,
        labor_hours: 1,
        labor_rate: 100,
        material_cost: 0,
        markup_percent: 0,
        tax_percent: 0,
        sort_order: 0,
      },
      {
        title: "Labor",
        description: "Licensed electrician labor",
        quantity: 1,
        unit: "hour",
        unit_price: 0,
        labor_hours: 2.5,
        labor_rate: 100,
        material_cost: 0,
        markup_percent: 0,
        tax_percent: 0,
        sort_order: 1,
      },
      {
        title: "Materials",
        description: "Electrical components and supplies",
        quantity: 1,
        unit: "lot",
        unit_price: 0,
        labor_hours: 0,
        labor_rate: 0,
        material_cost: 200,
        markup_percent: 20,
        tax_percent: 0,
        sort_order: 2,
      },
    ],
  },
  {
    key: "general_contractor",
    label: "General Contractor",
    description: "General construction and renovation",
    defaultItems: [
      {
        title: "Project Management",
        description: "Planning, coordination, and oversight",
        quantity: 1,
        unit: "project",
        unit_price: 500,
        labor_hours: 0,
        labor_rate: 0,
        material_cost: 0,
        markup_percent: 0,
        tax_percent: 0,
        sort_order: 0,
      },
      {
        title: "Labor",
        description: "Construction labor",
        quantity: 1,
        unit: "hour",
        unit_price: 0,
        labor_hours: 40,
        labor_rate: 75,
        material_cost: 0,
        markup_percent: 0,
        tax_percent: 0,
        sort_order: 1,
      },
      {
        title: "Materials",
        description: "Construction materials and supplies",
        quantity: 1,
        unit: "lot",
        unit_price: 0,
        labor_hours: 0,
        labor_rate: 0,
        material_cost: 2000,
        markup_percent: 30,
        tax_percent: 0,
        sort_order: 2,
      },
    ],
  },
  {
    key: "landscaping",
    label: "Landscaping",
    description: "Landscape design and maintenance",
    defaultItems: [
      {
        title: "Site Assessment",
        description: "Property evaluation and planning",
        quantity: 1,
        unit: "visit",
        unit_price: 0,
        labor_hours: 2,
        labor_rate: 65,
        material_cost: 0,
        markup_percent: 0,
        tax_percent: 0,
        sort_order: 0,
      },
      {
        title: "Labor",
        description: "Landscaping crew labor",
        quantity: 1,
        unit: "hour",
        unit_price: 0,
        labor_hours: 16,
        labor_rate: 65,
        material_cost: 0,
        markup_percent: 0,
        tax_percent: 0,
        sort_order: 1,
      },
      {
        title: "Plants & Materials",
        description: "Plants, soil, mulch, and supplies",
        quantity: 1,
        unit: "lot",
        unit_price: 0,
        labor_hours: 0,
        labor_rate: 0,
        material_cost: 800,
        markup_percent: 35,
        tax_percent: 0,
        sort_order: 2,
      },
    ],
  },
  {
    key: "roofing",
    label: "Roofing",
    description: "Roof repair and installation",
    defaultItems: [
      {
        title: "Roof Inspection",
        description: "Complete roof assessment",
        quantity: 1,
        unit: "visit",
        unit_price: 0,
        labor_hours: 1.5,
        labor_rate: 85,
        material_cost: 0,
        markup_percent: 0,
        tax_percent: 0,
        sort_order: 0,
      },
      {
        title: "Labor",
        description: "Roofing crew labor",
        quantity: 1,
        unit: "hour",
        unit_price: 0,
        labor_hours: 24,
        labor_rate: 85,
        material_cost: 0,
        markup_percent: 0,
        tax_percent: 0,
        sort_order: 1,
      },
      {
        title: "Roofing Materials",
        description: "Shingles, underlayment, and supplies",
        quantity: 1,
        unit: "lot",
        unit_price: 0,
        labor_hours: 0,
        labor_rate: 0,
        material_cost: 3000,
        markup_percent: 25,
        tax_percent: 0,
        sort_order: 2,
      },
    ],
  },
  {
    key: "painting",
    label: "Painting",
    description: "Interior and exterior painting",
    defaultItems: [
      {
        title: "Surface Preparation",
        description: "Cleaning, sanding, and priming",
        quantity: 1,
        unit: "project",
        unit_price: 0,
        labor_hours: 8,
        labor_rate: 55,
        material_cost: 100,
        markup_percent: 15,
        tax_percent: 0,
        sort_order: 0,
      },
      {
        title: "Painting Labor",
        description: "Professional painting service",
        quantity: 1,
        unit: "hour",
        unit_price: 0,
        labor_hours: 16,
        labor_rate: 55,
        material_cost: 0,
        markup_percent: 0,
        tax_percent: 0,
        sort_order: 1,
      },
      {
        title: "Paint & Supplies",
        description: "Paint, brushes, rollers, and materials",
        quantity: 1,
        unit: "lot",
        unit_price: 0,
        labor_hours: 0,
        labor_rate: 0,
        material_cost: 400,
        markup_percent: 20,
        tax_percent: 0,
        sort_order: 2,
      },
    ],
  },
  {
    key: "custom",
    label: "Custom / Blank",
    description: "Start from scratch",
    defaultItems: [
      {
        title: "Service",
        description: "",
        quantity: 1,
        unit: "unit",
        unit_price: 0,
        labor_hours: 0,
        labor_rate: 0,
        material_cost: 0,
        markup_percent: 0,
        tax_percent: 0,
        sort_order: 0,
      },
    ],
  },
];
