project_id = "yxsnqhuilqdvqrmkjxzf"

[functions.incoming-webhook]
verify_jwt = false

[functions.run-automations]
verify_jwt = false

[functions.generate-wallet-pass]
verify_jwt = false

[functions.generate-card-content]
verify_jwt = false

[functions.check-idle-leads]
verify_jwt = false